UMA/Controllers/RoleController.cs
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UMA.Models;
using UMA_Proxy;
using UMAentities;
using Helper = UMA.Helpers.Helper;

namespace UMA.Controllers
{
    [AuthorizeCustomAttribute]
    public class RoleController : Controller
    {
        public ActionResult CreateRole(BaseModel model, string selectedRoleApp, string roletype, string isAppLinked)
        {
            if (!string.IsNullOrEmpty(model.NewRoleName) && (!string.IsNullOrEmpty(selectedRoleApp) || isAppLinked == "0"))
            {
                int result = new RoleProxy().RoleChannel.AddRole(new Role() { Name = model.NewRoleName, RoleType = new RoleType() { RoleTypeId = int.Parse(roletype) }, ApplicationId = string.IsNullOrEmpty(selectedRoleApp) ? 0 : int.Parse(selectedRoleApp), OwnerId = int.Parse(User.Identity.GetUserId()) });

                if (result == 2)
                {
                    string error = "a role with this name already exists";
                    return Json(new { err = error }, JsonRequestBehavior.AllowGet);
                }

                // Get Roles to update screen
                if (isAppLinked == "1")
                {
                    if (selectedRoleApp != null)
                    {
                        var roles = new RoleProxy().RoleChannel.GetApplicationRoles(new Application
                        {
                            Id = int.Parse(selectedRoleApp),
                            RoleType = string.IsNullOrEmpty(roletype) ? 0 : int.Parse(roletype),
                            ExcludeLesserRoles = true
                        });
                        model.OperatorType = int.Parse(GenericPrincipalExtensions.GetClaim(User, "OperatorType"));
                        model.Roles = roles;
                    }
                }
                else
                {
                    var roles = new RoleProxy().RoleChannel.GetSystemRoles();
                    model.OperatorType = int.Parse(GenericPrincipalExtensions.GetClaim(User, "OperatorType"));
                    model.Roles = roles;
                }

                return Json(new { status = result, page = Helper.JsonPartialView(this, "RolePriviManagement/_EditRole", model) }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { status = 0, err = "You must select an application and then enter a role name" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AssignRolePrivileges(Role role)
        {
            if ((!string.IsNullOrEmpty(role.AddPrivileges) || !string.IsNullOrEmpty(role.AddRoles)) && role.Id != 0)
            {
                int result;

                // disect string
                if (!string.IsNullOrEmpty(role.AddPrivileges))
                {
                    List<Privilege> privis = new List<Privilege>();
                    foreach (string privi in role.AddPrivileges.Split(','))
                    {
                        Privilege p = new Privilege()
                        {
                            Id = int.Parse(privi),
                            RoleId = role.Id,
                            EditBy = int.Parse(User.Identity.GetUserId())
                        };

                        privis.Add(p);
                    }

                    result = new RoleProxy().RoleChannel.AddPrivilegesToRole(privis);
                }
                else
                {
                    List<Role> grps = new List<Role>();
                    foreach (string grp in role.AddRoles.Split(','))
                    {
                        Role p = new Role()
                        {
                            Id = int.Parse(grp),
                            AddToRole = role.Id,
                            EditBy = int.Parse(User.Identity.GetUserId())
                        };

                        grps.Add(p);
                    }

                    result = new RoleProxy().RoleChannel.AddRolesToRole(grps);
                }

                // Get updated role details
                Role updatedrole = new RoleProxy().RoleChannel.GetRoleDetails(role);
                return Json(new { status = result, page = Helper.JsonPartialView(this, "RolePriviManagement/_RolePriviPartial", updatedrole) }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { status = 0, err = "Select a role and select 1 or more privileges" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RemoveRolePrivileges(Role role)
        {
            if ((!string.IsNullOrEmpty(role.RemovePrivileges) || !string.IsNullOrEmpty(role.RemoveRoles)) && role.Id != 0)
            {
                int result;

                // disect string
                if (!string.IsNullOrEmpty(role.RemovePrivileges))
                {
                    List<Privilege> privis = new List<Privilege>();
                    foreach (string privi in role.RemovePrivileges.Split(','))
                    {
                        Privilege p = new Privilege()
                        {
                            Id = int.Parse(privi),
                            RoleId = role.Id,
                            EditBy = int.Parse(User.Identity.GetUserId())
                        };

                        privis.Add(p);
                    }

                    result = new RoleProxy().RoleChannel.RemovePrivilegesFromRole(privis);
                }
                else
                {
                    List<Role> roles = new List<Role>();
                    foreach (string grp in role.RemoveRoles.Split(','))
                    {
                        Role p = new Role()
                        {
                            Id = int.Parse(grp),
                            AddToRole = role.Id,
                            EditBy = int.Parse(User.Identity.GetUserId())
                        };

                        roles.Add(p);
                    }

                    result = new RoleProxy().RoleChannel.RemoveRolesFromRole(roles);
                }

                // Get updated role details
                Role updatedrole = new RoleProxy().RoleChannel.GetRoleDetails(role);
                return Json(new { status = result, page = Helper.JsonPartialView(this, "RolePriviManagement/_RolePriviPartial", updatedrole) }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { status = 0, err = "Select a role and select 1 or more privileges" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddRoleToRole(Role role)
        {
            if (!string.IsNullOrEmpty(role.AddPrivileges) && role.Id != 0)
            {
                role.Privileges = new List<Privilege>();
                role.EditBy = int.Parse(User.Identity.GetUserId());

                // disect string
                foreach (string privi in role.AddPrivileges.Split(','))
                {
                    Privilege p = new Privilege()
                    {
                        Id = int.Parse(privi)
                    };

                    role.Privileges.Add(p);
                }

                int result = new PrivilegeProxy().PrivilegeChannel.AddPrivilegesToGroup(role);

                // Get updated role details
                Role updatedgrp = new RoleProxy().RoleChannel.GetRoleDetails(role);
                return Json(new { status = result, page = Helper.JsonPartialView(this, "RolePriviManagement/_PriviGrpPartial", updatedgrp) }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { status = 0, err = "Select a role and select 1 or more privileges" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AssignRoles(string addRoles, string selectedOperator, string selectedRoleAppId)
        {
            if (!string.IsNullOrEmpty(addRoles) && !string.IsNullOrEmpty(selectedOperator) && !string.IsNullOrEmpty(selectedRoleAppId))
            {
                // disect string
                var roles = new List<Role>();
                foreach (string s in addRoles.Split(','))
                {
                    var r = new Role
                    {
                        Id = int.Parse(s),
                        OwnerId = int.Parse(selectedOperator),
                        EditBy = int.Parse(User.Identity.GetUserId())
                    };

                    roles.Add(r);
                }

                new RoleProxy().RoleChannel.AddRolesToOperator(roles);

                // Get updated role details
                return GetOperatorRoles(selectedOperator, selectedRoleAppId);
            }

            return Json(new { status = 0, err = "Select a role and select 1 or more privileges" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RemoveRoles(string removeRoles, string selectedOperator, string selectedRoleAppId)
        {
            if (!string.IsNullOrEmpty(removeRoles) && !string.IsNullOrEmpty(selectedOperator) && !string.IsNullOrEmpty(selectedRoleAppId))
            {
                // disect string
                var roles = new List<Role>();
                foreach (string s in removeRoles.Split(','))
                {
                    var r = new Role
                    {
                        Id = int.Parse(s),
                        OwnerId = int.Parse(selectedOperator)
                    };

                    roles.Add(r);
                }

                new RoleProxy().RoleChannel.RemoveRolesFromOperator(roles);

                // Get updated role details
                return GetOperatorRoles(selectedOperator, selectedRoleAppId);
            }

            return Json(new { status = 0, err = "Select a role and select 1 or more privileges" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateRole(Role role)
        {
            if (!string.IsNullOrEmpty(role.Name))

UMA/Views/Shared/RolePriviManagement/_EditPriviGroup.cshtml
@model UMA.Models.BaseModel
@using Microsoft.AspNet.Identity;

@if (Model == null || Model.PrivilegeGrps.Count == 0)
{
    <div class="noitemsmsg medfirstletter">No Privilege Groups added yet</div>
}
else
{
    var privigrps = Model.PrivilegeGrps.Where(x => x.OwnerId.ToString() == User.Identity.GetUserId()).ToList();
    if (privigrps.Count > 0)
    {
        <div class="spacebotx2">
            <div class="appgrpheader">My Privilege Groups</div>
            <hr class="hrclass" />
            @for (int i = 0; i < privigrps.Count; i++)
            {
                <div class="spacetop">
                    <form method="post" action="@Url.Action("UpdatePriviGroup", "Privilege")" data-uma-update="true" data-uma-success="Privilege Group successfully edited">
                        @Html.Hidden("Id", privigrps[i].Id)
                        @Html.TextBoxFor(m => m.PrivilegeGrps.Where(x => x.Id == privigrps[i].Id).FirstOrDefault().Name, new { @class = "left textbox2", placeholder = "Enter group name" })
                        <div class="genbutton privibtn left">Privileges</div>
                        <input type="submit" value="Edit" class="genbutton left" />
                        <div class="delbutton">Remove</div>
                        <div class="loadingdiv left">
                            <div class="smallmodal"></div>
                        </div>
                        <div class="clear"></div>
                        <div id="creatroleval" class="validationMessage hidden">@Html.ValidationMessageFor(m => m.PrivilegeGrps[i].Name)</div>
                    </form>
                    <form method="post" action="@Url.Action("DeletePriviGroup", "Privilege")" data-uma-del="true" data-uma-success="Privilege Group has been removed">
                        @Html.Hidden("Id", privigrps[i].Id)
                        <input type="submit" class="hidden hiddenclickdelrole" />
                        <div class="clear"></div>
                    </form>
                    <form method="post" action="@Url.Action("GetPriviGroupDetails", "Privilege")" data-uma-partial="true" data-uma-target="privigrpdiv@(privigrps[i].Id)">
                        @Html.Hidden("Id", privigrps[i].Id)
                        <input type="submit" class="hidden hiddenclickgetrole" />
                    </form>
                    <div id="privigrpdiv@(privigrps[i].Id)" class="roleprividiv hidden"></div>
                </div>
            }
        </div>
    }

    var others = Model.PrivilegeGrps.Where(x => x.OwnerId.ToString() != User.Identity.GetUserId()).ToList();
    if (others.Count > 0)
    {
        <div class="rolegrpheader">@(Model.OperatorType == 1 ? "Other" : "Default") PrivilegeGrps</div>
        <hr class="hrclass" />
        <ul>
            @for (int i = 0; i < others.Count; i++)
            {
                <li><div class="applicationNames">@others[i].Name <i class="smallertext">@others[i].OwnerName</i></div></li>
            }
        </ul>
    }
}

UMA/Views/Shared/RolePriviManagement/_EditPrivilege.cshtml
@model UMA.Models.BaseModel
@using Microsoft.AspNet.Identity;

@if (Model == null || Model.Privileges.Count == 0)
{
    <div class="noitemsmsg medfirstletter">No privileges added yet</div>
}
else
{
    var myprivis = Model.Privileges.Where(x => x.OwnerId.ToString() == User.Identity.GetUserId()).ToList();
    if (myprivis.Count > 0)
    {
        <div class="appgrpheader">My Privileges</div>
        <hr class="hrclass" />
        for (int i = 0; i < myprivis.Count; i++)
        {
            <div class="spacetop">
                <form method="post" action="@Url.Action("UpdatePrivi", "Privilege")" data-uma-update="true" data-uma-success="privilege successfully edited">
                    @Html.Hidden("Id", myprivis[i].Id)
                    @Html.Hidden("ApplicationId", myprivis[i].ApplicationId)
                    @Html.TextBoxFor(m => m.Privileges.Where(x => x.Id == myprivis[i].Id).FirstOrDefault().Name, new { @class = "left textbox2", placeholder = "Enter privilege name" })
                    <input type="submit" value="Edit" class="genbutton left" />
                    <div class="delbutton">Remove</div>
                    <div class="loadingdiv left">
                        <div class="smallmodal"></div>
                    </div>
                    <div class="clear"></div>
                    <div id="creatprivival" class="apperror validationMessage hidden">@Html.ValidationMessageFor(m => m.Privileges[i].Name)</div>
                </form>
                <form method="post" action="@Url.Action("DeletePrivi", "Privilege")" data-uma-del="true" data-uma-success="Privilege has been removed">
                    @Html.HiddenFor(m => m.Privileges.Where(x => x.Id == myprivis[i].Id).FirstOrDefault().Id)
                    <input type="submit" class="hidden hiddenclick" />
                    <div class="clear"></div>
                </form>
            </div>
        }
    }

    var others = Model.Privileges.Where(x => x.OwnerId.ToString() != User.Identity.GetUserId()).ToList();
    if (others.Count > 0)
    {
        <div class="appgrpheader spacetop">Privileges</div>
        <hr class="hrclass" />
        <div class="columns">
            <ul>
                @for (int i = 0; i < others.Count; i++)
                {
                    if (Model.OperatorType == 1)
                    {
                        <li><div class="applicationNames">@others[i].Name <i class="smallertext">(@others[i].OwnerName)</i></div></li>
                    }
                    else
                    {
                        <li><div class="applicationNames">@others[i].Name</div></li>
                    }
                }
            </ul>
        </div>
    }
}

UMA/Views/Shared/RolePriviManagement/_EditRole.cshtml
@model UMA.Models.BaseModel
@using Microsoft.AspNet.Identity;

@if (Model == null || Model.Roles.Count == 0)
{
    <div class="noitemsmsg medfirstletter">No Roles added yet</div>
}
else
{
    var myroles = Model.Roles.Where(x => x.OwnerId.ToString() == User.Identity.GetUserId()).ToList();
    if (myroles.Count > 0)
    {
        <div class="spacebotx2">
            <div class="appgrpheader">My Roles</div>
            <hr class="hrclass" />
            @for (int i = 0; i < myroles.Count; i++)
            {
                <div class="spacetop">
                    <form method="post" action="@Url.Action("UpdateRole")" data-uma-update="true" data-uma-success="Role successfully edited">
                        @Html.Hidden("Id", myroles[i].Id)
                        @Html.Hidden("ApplicationId", myroles[i].ApplicationId)
                        @Html.TextBoxFor(m => m.Roles.Where(x => x.Id == myroles[i].Id).FirstOrDefault().Name, new { @class = "left textbox2", placeholder = "Enter role name" })
                        <div class="genbutton privibtn left">Privileges</div>
                        <input type="submit" value="Edit" class="genbutton left" />
                        <div class="delbutton">Remove</div>
                        <div class="loadingdiv left">
                            <div class="smallmodal"></div>
                        </div>
                        <div class="clear"></div>
                        <div id="creatroleval" class="apperror validationMessage">@Html.ValidationMessageFor(m => m.Roles[i].Name)</div>
                    </form>
                    <form method="post" action="@Url.Action("DeleteRole")" data-uma-del="true" data-uma-success="Role has been removed">
                        @Html.HiddenFor(m => m.Roles.Where(x => x.Id == myroles[i].Id).FirstOrDefault().Id)
                        <input type="submit" class="hidden hiddenclickdelrole" />
                        <div class="clear"></div>
                    </form>
                    <form method="post" action="@Url.Action("GetRoleDetails")" data-uma-partial="true" data-uma-target="roleprividiv@(myroles[i].Id)">
                        @Html.Hidden("Id", myroles[i].Id)
                        @Html.Hidden("ApplicationId", myroles[i].ApplicationId)
                        <input type="submit" class="hidden hiddenclickgetrole" />
                    </form>
                    <div id="roleprividiv@(myroles[i].Id)" class="roleprividiv hidden"></div>
                </div>
            }
        </div>
    }

    var others = Model.Roles.Where(x => x.OwnerId.ToString() != User.Identity.GetUserId()).ToList();
    if (others.Count > 0)
    {
        <div class="rolegrpheader">@(Model.OperatorType == 1 ? "Other" : "Default") Roles</div>
        <hr class="hrclass" />
        <ul>
            @for (int i = 0; i < others.Count; i++)
            {
                <li><div class="applicationNames">@others[i].Name <i class="smallertext">@others[i].OwnerName</i></div></li>
            }
        </ul>
    }
}

UMA/Views/Shared/RolePriviManagement/_EditSystemRole.cshtml
@using UMAentities
@using Microsoft.AspNet.Identity;
@model List<Role>

@if (Model == null || Model.Count == 0)
{
    <div class="noitemsmsg medfirstletter">No Roles added yet</div>
}
else
{
    var myroles = Model.Where(x => x.OwnerId.ToString() == User.Identity.GetUserId()).ToList();
    if (myroles.Count > 0)
    {
        <div class="spacebotx2">
            <div class="appgrpheader">My Roles</div>
            <hr class="hrclass" />
            @for (int i = 0; i < myroles.Count; i++)
            {
                <div class="spacetop">
                    <form method="post" action="@Url.Action("UpdateRole", "Role")" data-uma-update="true" data-uma-success="Role successfully edited">
                        @Html.Hidden("Id", myroles[i].Id)
                        @Html.TextBoxFor(m => m.Where(x => x.Id == myroles[i].Id).FirstOrDefault().Name, new { @class = "left textbox2", placeholder = "Enter role name" })
                        <div class="genbutton privibtn left">Privileges</div>
                        <input type="submit" value="Edit" class="genbutton left" />
                        <div class="delbutton">Remove</div>
                        <div class="loadingdiv left">
                            <div class="smallmodal"></div>
                        </div>
                        <div class="clear"></div>
                        <div id="creatroleval" class="validationMessage">@Html.ValidationMessageFor(m => m[i].Name)</div>
                    </form>
                    <form method="post" action="@Url.Action("DeleteRole", "Role")" data-uma-del="true" data-uma-success="Role has been removed">
                        @Html.HiddenFor(m => m.Where(x => x.Id == myroles[i].Id).FirstOrDefault().Id)
                        <input type="submit" class="hidden hiddenclickdelrole" />
                        <div class="clear"></div>
                    </form>
                    <form method="post" action="@Url.Action("GetRoleDetails", "Role")" data-uma-partial="true" data-uma-target="roleprividiv@(myroles[i].Id)">
                        @Html.Hidden("Id", myroles[i].Id)
                        <input type="submit" class="hidden hiddenclickgetrole" />
                    </form>
                    <div id="roleprividiv@(myroles[i].Id)" class="roleprividiv hidden"></div>
                </div>
            }
        </div>
    }

    var others = Model.Where(x => x.OwnerId.ToString() != User.Identity.GetUserId()).ToList();
    if (others.Count > 0)
    {
        <div class="rolegrpheader">Other Roles</div>
        <hr class="hrclass" />
        <ul>
            @for (int i = 0; i < others.Count; i++)
            {
                <li><div class="applicationNames">@others[i].Name <i class="smallertext">@others[i].OwnerName</i></div></li>
            }
        </ul>
    }
}

UMA/Views/Shared/RolePriviManagement/_PriviGrpPartial.cshtml
@using UMAentities
@model Role

<div class="transferboxes">
    <div class="left bigbox leftsidebox">
        <div class="priviheading">Unassigned Privileges</div>
        @Html.TextBox("searchbox", null, new { @class = "searchbox" })
        <div id="unselpriviwrap@(Model.Id)" class="box">
            @foreach (Privilege privi in Model.UnselectedPrivileges)
            {
                <div id="addprivis@(privi.Id)" class="prividiv">@privi.Name</div>
            }
        </div>
    </div>
    <div class="left transferbtnbox">
        <form method="post" action="@Url.Action("AssignGroupPrivileges")" data-uma-partial="true" data-uma-target="privigrpdiv@(Model.Id)">
            @Html.Hidden("Id", Model.Id)
            @Html.Hidden("AddPrivileges", null, new { id = "AddPrivileges" + Model.Id })
            <input type="submit" class="genbutton transferbtn unfocused" value="Assign &rArr;" />
        </form>
        <form method="post" action="@Url.Action("RemoveGroupPrivileges")" data-uma-partial="true" data-uma-target="privigrpdiv@(Model.Id)">
            @Html.Hidden("RemovePrivileges", null, new { id = "RemovePrivileges" + Model.Id })
            @Html.Hidden("Id", Model.Id)
            <input type="submit" class="genbutton transferremovebtn unfocused" value="&lArr; Remove" />
        </form>
    </div>
    <div class="left bigbox rightsidebox">
        <div class="priviheading">Assigned Privileges</div>
        @Html.TextBox("searchbox", null, new { @class = "searchbox" })
        <div id="priviwrap@(Model.Id)" class="box">
            @foreach (Privilege privi in Model.Privileges)
            {
                <div id="removeprivis@(privi.Id)" class="prividiv">@privi.Name</div>
            }
        </div>
    </div>
    <div class="clear"></div>
</div>

UMA/Views/Shared/RolePriviManagement/_RoleOprPartial.cshtml
@using UMAentities
@model Operator

<div class="transferboxes">
    <div class="left bigbox leftsidebox">
        <div class="priviheading">Unassigned Roles</div>
        @Html.TextBox("searchbox", null, new { @class = "searchbox" })
        <div id="unselpriviwrap@(Model.OperatorId)" class="box">
            @foreach (Role role in Model.UnselectedRoles)
            {
                <div id="addprivis@(role.Id)" class="prividiv">@role.Name</div>
            }
        </div>
    </div>
    <div class="left transferbtnbox">
        <form method="post" action="@Url.Action("AssignRoles")" data-uma-partial="true" data-uma-target="@(Model.OperatorType == 1 ? "roleprividiv" + Model.OperatorId : "assignrolediv")">
            @Html.Hidden("SelectedOperator", Model.OperatorId)
            @Html.Hidden("SelectedRole")
            @Html.Hidden("SelectedRoleAppId", Model.AppId)
            @Html.Hidden("AddRoles", null, new { id = "AddPrivileges" + Model.OperatorId })
            <input type="submit" class="genbutton transferbtn unfocused" value="Assign &rArr;" />
        </form>
        <form method="post" action="@Url.Action("RemoveRoles")" data-uma-partial="true" data-uma-target="@(Model.OperatorType == 1 ? "roleprividiv" + Model.OperatorId : "assignrolediv")">
            @Html.Hidden("RemoveRoles", null, new { id = "RemovePrivileges" + Model.OperatorId })
            @Html.Hidden("SelectedRole")
            @Html.Hidden("SelectedRoleAppId", Model.AppId)
            @Html.Hidden("SelectedOperator", Model.OperatorId)
            <input type="submit" class="genbutton transferremovebtn unfocused" value="&lArr; Remove" />
        </form>
    </div>
    <div class="left bigbox rightsidebox">
        <div class="priviheading">Assigned Roles</div>
        @Html.TextBox("searchbox", null, new { @class = "searchbox" })
        <div id="priviwrap@(Model.OperatorId)" class="box">
            @foreach (Role role in Model.SelectedRoles)
            {
                <div id="removeprivis@(role.Id)" class="prividiv">@role.Name</div>
            }
        </div>
    </div>
    <div class="clear"></div>
</div>

UMA/Views/Shared/RolePriviManagement/_RolePriviPartial.cshtml
@using UMAentities
@model Role

<div class="privisortparent" id="test">
    @if (Model.RoleType.IsApplicationLinked == 0)
    {
        <div class="toppadding">
            @Html.Hidden("privifiltercombo", null, new { @class = "inline selectbox privisort spacetopx2" })
        </div>
    }

    <div class="transferboxes">
        <div class="left smallbox leftsidebox">
            <div class="priviheading">Unassigned Privileges</div>
            @Html.TextBox("searchbox", null, new { @class = "searchbox" })
            <div id="unselpriviwrap@(Model.Id)" class="box">
                @foreach (Privilege privi in Model.UnselectedPrivileges)
            {
            <div id="addprivis@(privi.Id)" class="prividiv app@(privi.ApplicationId)">@privi.Name</div>
            }
            </div>
        </div>
        <div class="left smallbox leftsidebox spaceleft">
            <div class="priviheading">Unassigned Roles</div>
            @Html.TextBox("searchbox", null, new { @class = "searchbox" })
            <div id="unselprivigrpwrap@(Model.Id)" class="box">
                @foreach (Role grp in Model.UnselectedRoles)
            {
            <div id="addprivigrp@(grp.Id)" class="privigrp app@(grp.ApplicationId)">@grp.Name</div>
            }
            </div>
        </div>
        <div class="left transferbtnbox">
            <form method="post" action="@Url.Action("AssignRolePrivileges")" data-uma-partial="true" data-uma-target="roleprividiv@(Model.Id)">
                @Html.Hidden("Id", Model.Id)
                @Html.Hidden("ApplicationId", Model.ApplicationId)
                @Html.Hidden("AddPrivileges", null, new { id = "AddPrivileges" + Model.Id })
                @Html.Hidden("AddRoles", null, new { id = "AddPrivilegeGroups" + Model.Id })
                <input type="submit" class="genbutton transferbtn unfocused" value="Assign &rArr;" />
            </form>
            <form method="post" action="@Url.Action("RemoveRolePrivileges")" data-uma-partial="true" data-uma-target="roleprividiv@(Model.Id)">
                @Html.Hidden("RemovePrivileges", null, new { id = "RemovePrivileges" + Model.Id })
                @Html.Hidden("RemoveRoles", null, new { id = "RemovePrivilegeGroups" + Model.Id })
                @Html.Hidden("Id", Model.Id)
                @Html.Hidden("ApplicationId", Model.ApplicationId)
                <input type="submit" class="genbutton transferremovebtn unfocused" value="&lArr; Remove" />
            </form>
        </div>
        <div class="left smallbox rightsidebox">
            <div class="priviheading">Assigned Privileges</div>
            @Html.TextBox("searchbox", null, new { @class = "searchbox" })
            <div id="priviwrap@(Model.Id)" class="box">
                @foreach (Privilege privi in Model.Privileges)
            {
            <div id="removeprivis@(privi.Id)" class="prividiv app@(privi.ApplicationId)">@privi.Name</div>
            }
            </div>
        </div>
        <div class="left smallbox rightsidebox spaceleft">
            <div class="priviheading">Assigned Roles</div>
            @Html.TextBox("searchbox", null, new { @class = "searchbox" })
            <div id="privigrpwrap@(Model.Id)" class="box">
                @foreach (Role grp in Model.SubRoles)
            {
            <div id="removeprivigrp@(grp.Id)" class="privigrp app@(grp.ApplicationId)">@grp.Name</div>
            }
            </div>
        </div>
        <div class="clear"></div>
    </div>

</div>

UMA/Views/Shared/RolePriviManagement/_RolesPartial.cshtml
<form method="post" action="@Url.Action("CreateRole")" data-uma-partial="true" data-uma-target="roleeditdiv" data-uma-success="Role successfully created">
    <div class="formatinfo">Format: "Biometrics operator", "Approval officer"</div>
    @Html.TextBoxFor(m => m.NewRoleName, new { @class = "left textbox2", placeholder = "Create new role" })
    <input type="submit" value="Create" class="genbutton left" />
    <div class="loadingdiv left">
        <div class="smallmodal"></div>
    </div>
    <div class="clear"></div>
    <div id="creatappval" class="validationMessage apperror hidden">@Html.ValidationMessageFor(m => m.NewRoleName)</div>
</form>
<div id="roleeditdiv" class="groupboxedit">@Html.Partial("_EditRole", Model.Roles)</div>