UMA/Controllers/ApplicationController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using UMA.Models;
using UMA_Proxy;
using UMAentities;
using Helper = UMA.Helpers.Helper;


namespace UMA.Controllers
{
    [AuthorizeCustom]
    public class ApplicationController : Controller
    {       
        public ActionResult GetApplications()
        {
            try
            {
                List<Application> result = new ApplicationProxy().ApplicationChannel.GetApplications();
                result = result.OrderBy(x => x.Name).ToList();
                var jsonList = new List<object>();

                foreach (Application app in result)
                {
                    jsonList.Add(new { text = app.Name, id = app.Id });
                }

                return Json(new { result = new JavaScriptSerializer().Serialize(jsonList) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = -1 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetMyApplications()
        {
            try
            {
                List<Application> result = new ApplicationProxy().ApplicationChannel.GetApplications();

                result = result.Where(x => x.OwnerId == int.Parse(User.Identity.GetUserId())).OrderBy(x => x.Name).ToList();
                var jsonList = new List<object>();

                foreach (Application app in result)
                {
                    jsonList.Add(new { text = app.Name, id = app.Id });
                }

                return Json(new { result = new JavaScriptSerializer().Serialize(jsonList) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = -1 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CreateApp(BaseModel model)
        {
            try
            {
                if (!string.IsNullOrEmpty(model.NewAppName))
                {
                    int result = new ApplicationProxy().ApplicationChannel.AddApplication(new Application() { Name = model.NewAppName, OwnerId = int.Parse(User.Identity.GetUserId()) });

                    if (result == 2)
                    {
                        string error = "An application with this name already exists";
                        return Json(new { err = error }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        // Get Applications to update screen
                        List<Application> apps = new ApplicationProxy().ApplicationChannel.GetApplications();
                        return Json(new { status = result, page = Helper.JsonPartialView(this, "ApplicationManagement/_EditApplication", apps) }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                    return Json(new { status = 0, err = "You must enter an application name" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = -1 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult UpdateApp(Application app)
        {
            try
            {
                if (!string.IsNullOrEmpty(app.Name))
                {
                    app.EditBy = int.Parse(User.Identity.GetUserId());

                    int result = new ApplicationProxy().ApplicationChannel.UpdateApplication(app);

                    if (result == 3)
                        return Json(new { status = 0, err = "An application already exists with this name" }, JsonRequestBehavior.AllowGet);

                    return Json(new { status = result }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new { status = 0, err = "You must enter an application name" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = -1 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult DeleteApp(Application app)
        {
            try
            {
                if (app != null)
                {
                    app.EditBy = int.Parse(User.Identity.GetUserId());

                    int result = new ApplicationProxy().ApplicationChannel.DeleteApplication(app);
                    return Json(new { status = result }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new { status = 0, err = "Error deleting application" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = -1 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetUmaUsers(string appid)
        {
            try
            {
                if (!string.IsNullOrEmpty(appid))
                {
                    List<Operator> result = new ApplicationProxy().ApplicationChannel.GetUmaUsers(new Application() { OwnerId = int.Parse(User.Identity.GetUserId()), Id = int.Parse(appid) });

                    result = result.OrderBy(x => x.FirstName).ToList();
                    var jsonList = new List<object>();

                    foreach (Operator op in result)
                    {
                        jsonList.Add(new { text = op.FullName, id = op.OperatorId });
                    }

                    return Json(new { result = new JavaScriptSerializer().Serialize(jsonList) }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new { result = -1 }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = -1 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetSharedAppDetails(BaseModel model)
        {
            try
            {
                if (!string.IsNullOrEmpty(model.SelectedSharedApp))
                {
                    model.AllowedStaff = new ApplicationProxy().ApplicationChannel.GetSharedAppUsers(new Application() { Id = int.Parse(model.SelectedSharedApp), OwnerId = int.Parse(User.Identity.GetUserId()) });
                    return Json(new { status = 1, page = Helper.JsonPartialView(this, "ApplicationManagement/_ShareApplication", model) }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new { status = 0, err = "You must enter an application name" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = -1 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetBranchAdmins(string branchid)
        {
            try
            {
                if (!string.IsNullOrEmpty(branchid))
                {
                    var model = new BaseModel
                    {
                        OperatorType = int.Parse(GenericPrincipalExtensions.GetClaim(User, "OperatorType")),
                        CreatedAdmins = new ApplicationProxy().ApplicationChannel.GetBranchAdmins(new Application()
                        {
                            OwnerId = int.Parse(User.Identity.GetUserId()),
                            BranchId = int.Parse(branchid)
                        })
                    };

                    return Json(new { status = 1, page = Helper.JsonPartialView(this, "ApplicationManagement/_ApplicationAdmins", model) }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { status = 0, err = "You must select a branch" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = -1 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetBranchUsers(string branchid)
        {
            try
            {
                if (!string.IsNullOrEmpty(branchid))
                {
                    var model = new BaseModel
                    {
                        OperatorType = int.Parse(GenericPrincipalExtensions.GetClaim(User, "OperatorType")),
                        BranchName = new BranchProxy().BranchChannel.GetBranchName(int.Parse(branchid)),
                        CreatedAdmins = new ApplicationProxy().ApplicationChannel.GetBranchUsers(new Application()
                        {
                            BranchId = int.Parse(branchid),
                            OwnerId = int.Parse(User.Identity.GetUserId())
                        })
                    };

                    return Json(new { status = 1, page = Helper.JsonPartialView(this, "ApplicationManagement/_ApplicationAdmins", model) }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { status = 0, err = "You must select a branch" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { status = -1 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult SaveSharedAppUsers(BaseModel model)
        {
            try
            {
                if (!string.IsNullOrEmpty(model.SelectedSharedUsers) && !string.IsNullOrEmpty(model.SelectedSharedAppSave))
                {
                    model.AllowedStaff = new ApplicationProxy().ApplicationChannel.SaveSharedAppUsers(new Application()
                    {
                        Id = int.Parse(model.SelectedSharedAppSave),
                        OwnerId = int.Parse(User.Identity.GetUserId()),

UMA/Views/Shared/ApplicationManagement/ApplicationSuperusers.cshtml
@model UMA.Models.BaseModel
<form method="post" action="@Url.Action("CreateSuperUser", "Application")" data-uma-partial="true" data-uma-target="createappadmindivsu">
    <div class="">
        @Html.TextBoxFor(m => m.NewAdminUsername, new { @class = "textbox2 left", placeholder = "Enter superuser's email" })
        <input type="submit" value="Create" class="genbutton left" />
        <div class="loadingdiv left">
            <div class="smallmodal"></div>
        </div>
        <div class="clear"></div><div id="adminsuperusrerr" class="validationMessage apperror hidden">@Html.ValidationMessageFor(m => m.NewAdminUsername)</div>
        <div class="clear"></div>
    </div>
</form>

@if (Model.SuperUsers.Count == 0)
{
    <div class="nostaffmsg medfirstletter">No superusers created yet</div>
}
else
{   
    <div class="appgrpheader spacetop">Created SuperUsers</div>
    <hr class="hrclass" />
    foreach (UMAentities.Operator o in Model.SuperUsers)
    {
        <form method="post" action="@Url.Action("DeactivateSuperUser", "Account")" data-uma-partial="true" data-uma-target="createappadmindivsu">
            <div class="spacetop">
                @if (o.IsActivated)
                {
                    @Html.Hidden("iscancel", 0)
                    @Html.Hidden("RemoveUserOprId", o.OperatorId, new { id = "RemoveUserOprId" + o.OperatorId })
                    <div class="left alloweduser">@(o.FullName)</div>
                    <input type="submit" id="deactivateopr@(o.OperatorId)" class="left delbutton deactivateopr" style="width: 85px; margin-left: 0px" value="Deactivate" />
                    <div class="loadingdiv left">
                        <div class="smallmodal"></div>
                    </div>
                    <div class="clear"></div>
                }
                else
                {
                    @Html.Hidden("iscancel", 1)
                    @Html.Hidden("RemoveUserOprId", o.OperatorId, new { id = "RemoveUserOprId" + o.OperatorId })
                    <div class="left alloweduser">@(o.EmailAddress) (Not yet activated)</div>
                    <input type="submit" id="deactivateopr@(o.OperatorId)" class="left delbutton deactivateopr" style="width: 70px; margin-left: 0px" value="Cancel" />
                    <div class="loadingdiv left">
                        <div class="smallmodal"></div>
                    </div>
                    <div class="clear"></div>
                }
            </div>
        </form>
    }
}

@if (Model.OperatorType == 1)
{
    @Scripts.Render("~/bundles/jqueryval")
}

UMA/Views/Shared/ApplicationManagement/_ApplicationAdmins.cshtml
@model UMA.Models.BaseModel
<form method="post" action="@Url.Action(Model.OperatorType == 1 ? "CreateBranchAdmin" : "Application")" data-uma-partial="true" data-uma-target="createappadmindiv">
    @Html.Hidden("CreateAdminAppId")
    @Html.Hidden("CreateAdminBranchId")
    <div class="paddingbotx2">
        @Html.TextBoxFor(m => m.NewAdminUsername, new { @class = "textbox2 left", placeholder = "Enter " + (Model.OperatorType == 1 ? "admin's" : "user's") + " email" })
        <input type="submit" value="Create" class="genbutton left" />
        <div class="loadingdiv left">
            <div class="smallmodal"></div>
        </div>
        <div class="clear"></div>
        <div id="adminusrerr" class="validationMessage hidden">@Html.ValidationMessageFor(m => m.NewAdminUsername)</div>
        <div class="clear"></div>
    </div>
    @*<div class="spacebot">
        @Html.PasswordFor(m => m.NewAdminPassword, new { @class = "textbox2", placeholder = "Enter " + (Model.OperatorType == 1 ? "admin's" : "user's") + " password" })
        <div id="adminpwerr" class="validationMessage hidden">@Html.ValidationMessageFor(m => m.NewAdminPassword)</div>
        <div class="clear"></div>
    </div>
    <div class="spacebot">
        @Html.PasswordFor(m => m.NewAdminPasswordConfirm, new { @class = "textbox2 left", placeholder = "Confirm " + (Model.OperatorType == 1 ? "admin's" : "user's") + " password" })
        <input type="submit" value="Create" class="genbutton left" />
        <div class="loadingdiv left">
            <div class="smallmodal"></div>
        </div>
        <div class="clear"></div>
        <div id="adminpwconerr" class="validationMessage apperror hidden">@Html.ValidationMessageFor(m => m.NewAdminPasswordConfirm)</div>
    </div>*@
</form>

@if (Model.CreatedAdmins.Count == 0)
{
    <div class="nostaffmsg medfirstletter">No @(Model.OperatorType == 1 ? "admins" : "users") created yet</div>
}
else
{
    <div class="appgrpheader">Created @(Model.OperatorType == 1 ? "Admins" : "Users")</div>
    <hr class="hrclass" />
    foreach (UMAentities.Operator o in Model.CreatedAdmins)
    {
        <form method="post" action="@Url.Action("DeactivateAccount", "Account")" data-uma-partial="true" data-uma-target="createappadmindiv">
            <div class="spacetop">
                @if (o.IsActivated)
                {
                    @Html.Hidden("iscancel", 0)
                    @Html.Hidden("RemoveUserOprId", o.OperatorId, new { id = "RemoveUserOprId" + o.OperatorId })
                    <div class="left alloweduser">@(o.FullName)</div>
                    <input type="submit" id="deactivateopr@(o.OperatorId)" class="left delbutton deactivateopr" style="width: 85px; margin-left: 0px" value="Deactivate" />
                    <div class="loadingdiv left">
                        <div class="smallmodal"></div>
                    </div>
                    <div class="clear"></div>
                }
                else
                {
                    @Html.Hidden("iscancel", 1)
                    @Html.Hidden("RemoveUserOprId", o.OperatorId, new { id = "RemoveUserOprId" + o.OperatorId })
                    <div class="left alloweduser">@(o.EmailAddress) (Not yet activated)</div>
                    <input type="submit" id="deactivateopr@(o.OperatorId)" class="left delbutton deactivateopr" style="width: 70px; margin-left: 0px" value="Cancel" />
                    <div class="loadingdiv left">
                        <div class="smallmodal"></div>
                    </div>
                    <div class="clear"></div>
                }
            </div>
        </form>
    }
}

@if(Model.OperatorType == 1)
{ 
    @Scripts.Render("~/bundles/jqueryval")
}

UMA/Views/Shared/ApplicationManagement/_EditApplication.cshtml
@using Microsoft.AspNet.Identity;
@model List<UMAentities.Application>

@if (Model == null || Model.Count == 0)
{
    <div class="noitemsmsg medfirstletter">No applications added yet</div>
}
else
{
    var myapps = Model.Where(x => x.OwnerId.ToString() == User.Identity.GetUserId() || x.SharedWith.Contains(User.Identity.GetUserId())).ToList();
    if (myapps.Count > 0)
    {
        <div class="spacebotx2">
            <div class="appgrpheader">My Applications</div>
            <hr class="hrclass" />
            @for (int i = 0; i < myapps.Count; i++)
            {
                <div class="spacetop">
                    <form method="post" action="@Url.Action("UpdateApp", "Application")" data-uma-update="true" data-uma-success="Application successfully edited">
                        @Html.Hidden("Id", myapps[i].Id)
                        @Html.TextBoxFor(m => m.Where(x => x.Id == myapps[i].Id).FirstOrDefault().Name, new { @class = "left textbox2", placeholder = "Enter application name" })
                        <input type="submit" value="Edit" class="genbutton left" />
                        <div class="delbutton">Remove</div>
                        <div class="loadingdiv left">
                            <div class="smallmodal"></div>
                        </div>
                        <div class="clear"></div>
                        <div id="creatappval" class="apperror validationMessage hidden">@Html.ValidationMessageFor(m => m[i].Name)</div>
                    </form>
                    <form method="post" action="@Url.Action("DeleteApp", "Application")" data-uma-del="true" data-uma-success="Application has been removed">
                        @Html.HiddenFor(m => m.Where(x => x.Id == myapps[i].Id).FirstOrDefault().Id)
                        <input type="submit" class="hidden hiddenclickdelrole" />
                        <div class="clear"></div>
                    </form>
                </div>
            }
        </div>
    }

    var others = Model.Where(x => x.OwnerId.ToString() != User.Identity.GetUserId()).ToList();
    if (others.Count > 0)
    {
        <div class="appgrpheader">Other Applications</div>
        <hr class="hrclass" />
        <ul>
            @for (int i = 0; i < others.Count; i++)
            {
                <li><div class="applicationNames">@others[i].Name <i class="smallertext">(@others[i].OwnerName)</i></div></li>
            }
        </ul>
    }
}

UMA/Views/Shared/ApplicationManagement/_ShareApplication.cshtml
@model UMA.Models.BaseModel
<div class="left selectstaffdiv">
    @Html.Hidden("cmbSelectStaff", null, new { id = "cmbSelectStaff", @style = "width:400px;" })
</div>
<form method="post" action="@Url.Action("SaveSharedAppUsers")" data-uma-partial="true" data-uma-target="shareappdiv">
    @Html.Hidden("SelectedSharedUsers")
    @Html.Hidden("SelectedSharedAppSave")
    <input type="submit" class="genbutton left" value="Share" />
    <div class="loadingdiv left shiftspinnerup">
        <div class="smallmodal"></div>
    </div>
    <div class="clear"></div>
</form>
<div class="clear"></div>

@if (Model.AllowedStaff.Count == 0)
{
    <div class="nostaffmsg medfirstletter">Not shared with anyone</div>
}
else
{
    <div class="appgrpheader spacetop">Shared With</div>
    <hr class="hrclass" />
    foreach (UMAentities.Operator o in Model.AllowedStaff)
    {
        <form method="post" action="@Url.Action("RemoveShareApp")" data-uma-partial="true" data-uma-target="shareappdiv">
            @Html.Hidden("SelectedSharedAppRemove")
            @Html.Hidden("RemoveShareAppId", o.OperatorId)
            <div class="spacetop">
                <div class="left alloweduser" style="min-width: 385px">@(o.FullName)</div>
                <input type="submit" class="left delbutton" value="Remove" />
                <div class="loadingdiv left shiftspinnerup">
                    <div class="smallmodal"></div>
                </div>
                <div class="clear"></div>
            </div>
        </form>
    }
}